#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 29 11:28:35 2018

@author: hkyeremateng-boateng
"""

- One line pers sample - one the row put all attributes for signal.
- Method: Kasai (Anthony), SVR(hubert)

Support Vector regresion predicts
Goal: 